// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxK4PA8T3j5dIeiuO0tj8HzP0oVeHi-RY',
    appId: '1:405977450137:web:34ba31e6b0ce489a809a08',
    messagingSenderId: '405977450137',
    projectId: 'med-intel-d0b1e',
    authDomain: 'med-intel-d0b1e.firebaseapp.com',
    storageBucket: 'med-intel-d0b1e.firebasestorage.app',
    measurementId: 'G-7TF2W23LZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz-BFlWuA1T8luMYP2nwjlsYjHC3FLrsA',
    appId: '1:405977450137:android:6244a7d3b1a7efa6809a08',
    messagingSenderId: '405977450137',
    projectId: 'med-intel-d0b1e',
    storageBucket: 'med-intel-d0b1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHAcAzDGfbqPzBsMeG6enpJVPv3hEcB94',
    appId: '1:405977450137:ios:5d84c8ab1ba9dc10809a08',
    messagingSenderId: '405977450137',
    projectId: 'med-intel-d0b1e',
    storageBucket: 'med-intel-d0b1e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHAcAzDGfbqPzBsMeG6enpJVPv3hEcB94',
    appId: '1:405977450137:ios:5d84c8ab1ba9dc10809a08',
    messagingSenderId: '405977450137',
    projectId: 'med-intel-d0b1e',
    storageBucket: 'med-intel-d0b1e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxK4PA8T3j5dIeiuO0tj8HzP0oVeHi-RY',
    appId: '1:405977450137:web:5e887fc47703edf9809a08',
    messagingSenderId: '405977450137',
    projectId: 'med-intel-d0b1e',
    authDomain: 'med-intel-d0b1e.firebaseapp.com',
    storageBucket: 'med-intel-d0b1e.firebasestorage.app',
    measurementId: 'G-G5BXH3NG0Z',
  );
}
